<a href="https://colab.research.google.com/github/Khanbir/Data_analitycs/blob/main/DZ_3_4_apply%2C_groupby%2C_pivot_table_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [50]:
import pandas as pd
df = pd.read_csv('drive/MyDrive/DATA-ANALITICS_ Pylieva/supermarket_sales.csv')
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [51]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [52]:
df.groupby (["Branch"])['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [53]:
df.groupby(['Branch', 'City'])['Total'].sum()

Branch  City
A       Yangon       106200.3705
B       Mandalay     106197.6720
C       Naypyitaw    110568.7065
Name: Total, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [26]:
invoices_by_category = df.pivot_table(
    index='Branch',
    columns='Product line',
    values='Invoice ID',
    aggfunc='count',
    )
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [56]:
max_branch = invoices_by_category['Electronic accessories'].idxmax()
max_value = invoices_by_category['Electronic accessories'].max()

print(f'Найбільше інвойсів для Electronic accessories у філії {max_branch} — {max_value} покупок.')

Найбільше інвойсів для Electronic accessories у філії Yangon — 60 покупок.

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

Для отримання більше відповідей щодо стану справ у підпорядкованих філіалах хотілося отримати відповіді:
1. в яких магазинах (містах) які товари користуються більшим рейтингом?
2. в яких магазинах меншим рейтингом?
3. в які дні пікове навантаження?

In [69]:
invoices_by_city_cat = df.pivot_table(
    index='City',
    columns='Product line',
    values='Rating',
    aggfunc='mean',
    )
invoices_by_city_cat

max_city = invoices_by_city_cat.idxmax()
min_city = invoices_by_city_cat.idxmin()
display ('Товари з максимальними рейтингами по містах', max_city, 'Товари з мінімальними рейтингами по містах', min_city)

'Товари з максимальними рейтингами по містах'

Product line
Electronic accessories     Mandalay
Fashion accessories       Naypyitaw
Food and beverages           Yangon
Health and beauty          Mandalay
Home and lifestyle        Naypyitaw
Sports and travel            Yangon
dtype: object

'Товари з мінімальними рейтингами по містах'

Product line
Electronic accessories    Naypyitaw
Fashion accessories        Mandalay
Food and beverages         Mandalay
Health and beauty            Yangon
Home and lifestyle         Mandalay
Sports and travel          Mandalay
dtype: object

In [73]:
df['Date'] = pd.to_datetime(df['Date'])
df['Weekday'] = df['Date'].dt.day_name()

low_sales_by_branch = df.groupby(['City', 'Weekday'])['Total'].sum().reset_index()
least_busy_day = low_sales_by_branch.sort_values(['City', 'Total']).groupby('City').first()
least_busy_day

             Weekday       Total
City
Mandalay      Sunday  10415.3280
Naypyitaw     Monday  10925.3130
Yangon     Wednesday  13267.7265

Провівши додаткові розрахунки та проаналізувавши отримані дані можемо побачити що:
1. у місті Mandalay найнижчий рейтинг мають відразу 4 з 6 категорії товарів: Fashion accessories, Food and beverages, Home and lifestyle, Sports and travel і тільки Electronic accessories - найвищий рейтинг.
Як на мій погляд: Продукти одразу чотирьох категорій мають найнижчі оцінки в Mandalay — це системна проблема.
Для вирішення дного питання -  пнропозиція провести локальний аудит постачальників та переглянути якість товарів.
А також для більшої інформативності можна запустити опитування клієнтів Mandalay на касі/онлайн: “Що не так із нашими товарами?”.
Ну як варіант для виправлення ситуації -
Запровадити тимчасові знижки на ці категорії, супроводжуючи їх акціями “Ми вдосконалились!” після змін.
2. У Yangon варто розвимвати товари преміум сегмента та як тут товари з найвищим рейтингом:
Food and beverages та Sports and travel. А ось Health and beauty — має найнижчий рейтинг.
Можна зробити висновок - клієнти Yangon найбільш задоволені їжею та туристичними товарами → їх можна позиціонувати як преміум-продукти.
Користуючись цим як варіант бізнес-рішення:
запустити в Yangon преміальні набори делікатесів та спортивного спорядження.
А для категорії Health and beauty: переоцінити бренд/асортимент або замінити постачальника.
3. З аналізу продажів за днями тижня можна сказати що у кожній філії — свій оптимальний “прайм-тайм” для промоакцій згідно пікової активності клієнтів.
Що нам це дає - можна налаштувати рекламу не універсально а під кожну філію окремо.
А також сприрающись на дані активності покупців можемо корегувати задіяність персоналу магазину.